#cloud-config
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - nginx

package_update: true

runcmd:
  - [ systemctl, enable, nginx ]
  - [ systemctl, start, --no-block, nginx ]
  - [ systemctl, daemon-reload ]